### ISSUE TITLE
Can't Compile - Linkage issue

### ISSUE THREAD

**Issue by callowaysutton** [ThomasJaeger/VisualMASM#3]
I can't compile or debug because a file isn't found...
Version: Repo from 9-9-2017 and 9-10-2017
My OS: Windows 10 64 Home Bit
x64 Intel Core i3 Processor (idk might be helpful for something :P)
![visualmasm_2017-09-11_11-42-15](https://user-images.githubusercontent.com/7758184/30285459-2a7ab980-96ec-11e7-98a4-cf6b4d015dda.png)

**Comment by ThomasJaeger** [comment]
I fixed in the latest release just now. Please remove your current project from the Project Manager and create a new dialog project. It should work now. 

Please let me know if you still see any issues and I will re-open this ticket.

**Comment by callowaysutton** [comment]
Hm... There still seems to be an issue to linking files
![visualmasm_2017-09-11_11-42-15](https://i.imgur.com/Vd8WsDU.png)

**Comment by ThomasJaeger** [comment]
Can you attach your project as a zip file here and I will take a closer look? I will look at it later tonight then.

**Comment by ThomasJaeger** [comment]
The problem was that when creating dialog projects, Visual MASM was using an incorrect internal id to identify the source assembly file correctly. I also added additional checks during the assembly process.

This should be fixed now in the latest version. Please go ahead and try again. Note that you will need to create a new dialog project for this work correctly. Existing dialog projects won't work correctly unless you delete the assembly source file and add a new one. That will work as well.

Please provide feedback here once you have tried the new version.

**Comment by callowaysutton** [comment]
Everything is good now, thank you for all that you've done :)

**Comment by ThomasJaeger** [comment]
Awesome, glad its working now. Thanks for your feedback.
